services:
  backend:
    build:
      context: ./TaskFlow_serverSide
      dockerfile: Dockerfile
    ports:
      - 3000:8080  # Esponi la porta 8080 per il backend
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/taskflowdb
    volumes:
      - ./TaskFlow_serverSide:/app  # Monta la directory del backend
    command: mvn spring-boot:run  # Avvia con spring-boot:run per supportare l'hot reload

  frontend:
    build:
      context: ./TaskFlow_clientSide
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Mappa la porta 4200 del container alla porta 4200 dell'host
    volumes:
      - ./TaskFlow_clientSide:/app  # Monta la directory del progetto per il live reload
      - /app/node_modules  # Usa il node_modules dentro il container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Configurazione per il live reload su file system

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  node_modules:  # Definisce il volume nominato per node_modules